#!/bin/bash
set -euo pipefail

#######################################################################
# Contoso Meals - Full Deployment Script
# Deploys all Azure infrastructure + AKS workloads + configures services
# Generates .env file with all service endpoints for scripts to consume.
#######################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_ROOT}/.env"

# Ensure BuildKit is used for cross-platform Docker builds (arm64 host → amd64 images)
export DOCKER_BUILDKIT=1

# Configuration
RESOURCE_GROUP="rg-contoso-meals"
AKS_CLUSTER="aks-contoso-meals"
PREFIX="contoso-meals"
LOCATION="swedencentral"
POSTGRES_LOCATION="swedencentral"
POSTGRES_ADMIN="contosoadmin"
POSTGRES_PASSWORD="P@ssw0rd1234!"
LOAD_TEST_RESOURCE="lt-${PREFIX}"

echo "============================================="
echo "  Contoso Meals - Full Deployment"
echo "============================================="
echo ""

# Step 1: Deploy infrastructure via Bicep
echo "[1/9] Deploying Azure infrastructure (Bicep + AVM)..."
DEPLOYMENT_NAME="contoso-meals-$(date +%Y%m%d%H%M%S)"
az deployment sub create \
  --location "$LOCATION" \
  --template-file "$PROJECT_ROOT/infra/main.bicep" \
  --parameters "$PROJECT_ROOT/infra/main.parameters.json" \
  --name "$DEPLOYMENT_NAME" \
  --verbose

echo "  Infrastructure deployment complete."

# Step 2: Retrieve deployment outputs
echo "[2/9] Retrieving deployment outputs..."

POSTGRES_FQDN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.postgresServerFqdn.value" -o tsv)

MENU_API_FQDN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.menuApiFqdn.value" -o tsv)

SRE_MI_CLIENT_ID=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.sreAgentIdentityClientId.value" -o tsv 2>/dev/null || echo "")

SRE_AGENT_PORTAL_URL=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.sreAgentPortalUrl.value" -o tsv 2>/dev/null || echo "")

WEBUI_FQDN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.webUiFqdn.value" -o tsv 2>/dev/null || echo "")

CONTAINER_APP_DOMAIN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.containerAppEnvDefaultDomain.value" -o tsv 2>/dev/null || echo "")

JIRA_FQDN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.jiraSmFqdn.value" -o tsv 2>/dev/null || echo "")

MCP_FQDN=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.mcpAtlassianFqdn.value" -o tsv 2>/dev/null || echo "")

SRE_AGENT_ID=$(az deployment sub show --name "$DEPLOYMENT_NAME" \
  --query "properties.outputs.sreAgentId.value" -o tsv 2>/dev/null || echo "")

echo "  PostgreSQL FQDN:        $POSTGRES_FQDN"
echo "  Menu API FQDN:          $MENU_API_FQDN"
echo "  SRE Agent MI Client ID: $SRE_MI_CLIENT_ID"
if [ -n "$SRE_AGENT_PORTAL_URL" ]; then
  echo "  SRE Agent Portal URL:   $SRE_AGENT_PORTAL_URL"
fi

# Assign SRE Agent Administrator role to the deployer (idempotent — safe on re-deployment)
if [ -n "$SRE_AGENT_ID" ]; then
  echo "  Assigning SRE Agent Administrator role to deployer..."
  DEPLOYER_OID=$(az ad signed-in-user show --query id -o tsv 2>/dev/null || echo "")
  if [ -n "$DEPLOYER_OID" ]; then
    az role assignment create \
      --assignee-object-id "$DEPLOYER_OID" \
      --assignee-principal-type "User" \
      --role "e79298df-d852-4c6d-84f9-5d13249d1e55" \
      --scope "$SRE_AGENT_ID" \
      --only-show-errors 2>/dev/null || echo "  (Role assignment already exists — OK)"
    echo "  SRE Agent Administrator role assigned."
  else
    echo "  WARNING: Could not determine deployer identity. Assign SRE Agent Administrator role manually."
  fi
fi

# Generate initial .env with Bicep outputs (AKS IPs will be appended after Step 7)
echo "  Generating initial .env file with Bicep outputs..."
{
  echo "# Contoso Meals - Service Endpoints"
  echo "# Auto-generated by deploy.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "# Container App endpoints"
  echo "MENU_API_URL=https://${MENU_API_FQDN}"
  echo "WEB_UI_URL=https://${WEBUI_FQDN:-web-ui.${CONTAINER_APP_DOMAIN}}"
  echo ""
  echo "# AKS LoadBalancer endpoints (updated after AKS deployment)"
  echo "ORDER_API_URL=http://<pending>"
  echo "PAYMENT_API_URL=http://<pending>"
  echo ""
  echo "# Jira Service Management"
  echo "JIRA_URL=https://${JIRA_FQDN:-jira-sm.${CONTAINER_APP_DOMAIN}}"
  echo ""
  echo "# MCP Atlassian Server"
  echo "MCP_ATLASSIAN_URL=https://${MCP_FQDN:-mcp-atlassian.${CONTAINER_APP_DOMAIN}}/mcp"
  echo ""
  echo "# Azure resource identifiers"
  echo "RESOURCE_GROUP=${RESOURCE_GROUP}"
  echo "AKS_CLUSTER=${AKS_CLUSTER}"
  echo "LOAD_TEST_RESOURCE=${LOAD_TEST_RESOURCE}"
  echo ""
  echo "# PostgreSQL"
  echo "POSTGRES_FQDN=${POSTGRES_FQDN}"
  echo ""
  echo "# SRE Agent"
  echo "SRE_AGENT_PORTAL_URL=${SRE_AGENT_PORTAL_URL:-}"
  echo "SRE_AGENT_IDENTITY_CLIENT_ID=${SRE_MI_CLIENT_ID:-}"
} > "$ENV_FILE"
echo "  .env file written to ${ENV_FILE}"

# Step 3: Get AKS credentials (AKS Automatic uses Entra ID RBAC)
echo "[3/9] Getting AKS credentials..."
echo "  NOTE: AKS Automatic uses Entra ID RBAC. Ensure you have"
echo "        'Azure Kubernetes Service RBAC Cluster Admin' role on the cluster."
az aks get-credentials \
  --resource-group "$RESOURCE_GROUP" \
  --name "$AKS_CLUSTER" \
  --overwrite-existing

# Step 4: Create namespace
echo "[4/9] Creating Kubernetes namespace..."
kubectl apply -f "$PROJECT_ROOT/manifests/namespace.yaml" --validate=false

# Step 5: Create secrets
echo "[5/9] Creating Kubernetes secrets..."

# Get Application Insights connection string
APPINSIGHTS_CS=$(az monitor app-insights component show \
  --resource-group "$RESOURCE_GROUP" \
  --query "[0].connectionString" -o tsv 2>/dev/null || echo "")

if [ -z "$APPINSIGHTS_CS" ]; then
  echo "  WARNING: Application Insights connection string not found. Using placeholder."
  APPINSIGHTS_CS="InstrumentationKey=00000000-0000-0000-0000-000000000000"
fi

# Generate secrets from template
POSTGRES_CONNECTION_STRING="Host=${POSTGRES_FQDN};Database=ordersdb;Username=${POSTGRES_ADMIN};Password=${POSTGRES_PASSWORD};SSL Mode=Require;Trust Server Certificate=true"

kubectl create secret generic contoso-meals-secrets \
  --namespace production \
  --from-literal="orders-db-connection-string=${POSTGRES_CONNECTION_STRING}" \
  --from-literal="appinsights-connection-string=${APPINSIGHTS_CS}" \
  --dry-run=client -o yaml | kubectl apply -f -

echo "  Secrets created."

# Step 6: Build and push container images (if ACR exists)
echo "[6/9] Checking for Azure Container Registry..."
ACR_NAME=$(az acr list --resource-group "$RESOURCE_GROUP" --query "[0].name" -o tsv 2>/dev/null || echo "")

if [ -n "$ACR_NAME" ]; then
  echo "  ACR found: $ACR_NAME. Building and pushing images..."

  az acr build --registry "$ACR_NAME" \
    --image contoso-meals/order-api:latest \
    --platform linux/amd64 \
    "$PROJECT_ROOT/app/order-api/"

  az acr build --registry "$ACR_NAME" \
    --image contoso-meals/payment-service:latest \
    --platform linux/amd64 \
    "$PROJECT_ROOT/app/payment-service/"

  az acr build --registry "$ACR_NAME" \
    --image contoso-meals/web-ui:latest \
    --platform linux/amd64 \
    "$PROJECT_ROOT/app/web-ui/"

  # Update manifests with ACR name
  sed -i "s|\${ACR_NAME}|${ACR_NAME}|g" "$PROJECT_ROOT/manifests/order-api.yaml"
  sed -i "s|\${ACR_NAME}|${ACR_NAME}|g" "$PROJECT_ROOT/manifests/payment-service.yaml"
else
  echo "  No ACR found. Using pre-built images or placeholder images."
  echo "  To deploy with real images, create an ACR and re-run this script."

  # Replace image references with the .NET sample app as placeholder
  sed -i "s|\${ACR_NAME}.azurecr.io/contoso-meals/order-api:latest|mcr.microsoft.com/dotnet/samples:aspnetapp|g" "$PROJECT_ROOT/manifests/order-api.yaml"
  sed -i "s|\${ACR_NAME}.azurecr.io/contoso-meals/payment-service:latest|mcr.microsoft.com/dotnet/samples:aspnetapp|g" "$PROJECT_ROOT/manifests/payment-service.yaml"
fi

# Step 7: Deploy AKS workloads
echo "[7/9] Deploying AKS workloads..."
kubectl apply -f "$PROJECT_ROOT/manifests/order-api.yaml"
kubectl apply -f "$PROJECT_ROOT/manifests/payment-service.yaml"

echo "  Waiting for deployments to be ready..."
kubectl rollout status deployment/order-api -n production --timeout=120s || true
kubectl rollout status deployment/payment-service -n production --timeout=120s || true

# Wait for LoadBalancer external IPs and configure web-ui backend URLs
echo "  Waiting for AKS LoadBalancer external IPs..."
ORDER_API_IP=""
PAYMENT_SERVICE_IP=""
for i in $(seq 1 30); do
  ORDER_API_IP=$(kubectl get svc order-api -n production -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
  PAYMENT_SERVICE_IP=$(kubectl get svc payment-service -n production -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
  if [ -n "$ORDER_API_IP" ] && [ -n "$PAYMENT_SERVICE_IP" ]; then
    break
  fi
  echo "  Waiting for external IPs... (attempt $i/30)"
  sleep 10
done

if [ -n "$ORDER_API_IP" ] && [ -n "$PAYMENT_SERVICE_IP" ]; then
  echo "  Order API external IP:      $ORDER_API_IP"
  echo "  Payment Service external IP: $PAYMENT_SERVICE_IP"
  echo "  Updating web-ui Container App with AKS backend URLs..."
  az containerapp update \
    --name web-ui \
    --resource-group "$RESOURCE_GROUP" \
    --set-env-vars \
      "ORDER_API_URL=http://${ORDER_API_IP}" \
      "PAYMENT_API_URL=http://${PAYMENT_SERVICE_IP}" \
    --only-show-errors 2>/dev/null || echo "  WARNING: Failed to update web-ui with AKS backend URLs."
  echo "  web-ui backend URLs configured."
else
  echo "  WARNING: Could not retrieve AKS external IPs. web-ui may not connect to order-api/payment-service."
  echo "  order-api IP: ${ORDER_API_IP:-not assigned}"
  echo "  payment-service IP: ${PAYMENT_SERVICE_IP:-not assigned}"
fi

# Update web-ui Container App with built image
if [ -n "$ACR_NAME" ]; then
  echo "  Updating web-ui Container App image..."
  az containerapp update \
    --name web-ui \
    --resource-group "$RESOURCE_GROUP" \
    --image "${ACR_NAME}.azurecr.io/contoso-meals/web-ui:latest" \
    --only-show-errors 2>/dev/null || echo "  WARNING: Failed to update web-ui container app image."
fi

# Step 8: Update .env file with AKS LoadBalancer IPs
echo "[8/9] Updating .env file with AKS endpoints..."
if [ -n "${ORDER_API_IP:-}" ] && [ -n "${PAYMENT_SERVICE_IP:-}" ]; then
  sed -i "s|ORDER_API_URL=http://<pending>|ORDER_API_URL=http://${ORDER_API_IP}|" "$ENV_FILE"
  sed -i "s|PAYMENT_API_URL=http://<pending>|PAYMENT_API_URL=http://${PAYMENT_SERVICE_IP}|" "$ENV_FILE"
  echo "  .env updated with AKS IPs."
else
  echo "  WARNING: AKS IPs not available. .env has <pending> placeholders."
fi

# Step 8b: Setup Azure Load Testing test configurations
echo "  Setting up Azure Load Testing tests..."

MENU_API_HOST="${MENU_API_FQDN}"
ORDER_API_HOST="${ORDER_API_IP:-}"
PAYMENT_HOST="${PAYMENT_SERVICE_IP:-}"

if [ -n "$ORDER_API_HOST" ] && [ -n "$PAYMENT_HOST" ]; then
  LOAD_TEST_ENV="MENU_API_HOST=${MENU_API_HOST} ORDER_API_HOST=${ORDER_API_HOST} PAYMENT_HOST=${PAYMENT_HOST}"

  # Create or update baseline test
  if az load test show --load-test-resource "$LOAD_TEST_RESOURCE" --resource-group "$RESOURCE_GROUP" --test-id "baseline" -o none 2>/dev/null; then
    echo "  Updating existing baseline test..."
    az load test update \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "baseline" \
      --test-plan "$PROJECT_ROOT/load-tests/baseline.jmx" \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  else
    echo "  Creating baseline test..."
    az load test create \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "baseline" \
      --display-name "Contoso Meals - Baseline Traffic" \
      --test-plan "$PROJECT_ROOT/load-tests/baseline.jmx" \
      --engine-instances 1 \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  fi
  echo "  Baseline load test configured."

  # Create or update lunch-rush test
  if az load test show --load-test-resource "$LOAD_TEST_RESOURCE" --resource-group "$RESOURCE_GROUP" --test-id "lunch-rush" -o none 2>/dev/null; then
    echo "  Updating existing lunch-rush test..."
    az load test update \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "lunch-rush" \
      --test-plan "$PROJECT_ROOT/load-tests/lunch-rush.jmx" \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  else
    echo "  Creating lunch-rush test..."
    az load test create \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "lunch-rush" \
      --display-name "Contoso Meals - Lunch Rush" \
      --test-plan "$PROJECT_ROOT/load-tests/lunch-rush.jmx" \
      --engine-instances 1 \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  fi
  echo "  Lunch rush load test configured."
else
  echo "  WARNING: AKS IPs not available. Skipping load test configuration."
  echo "  Run load test setup manually after IPs are assigned."
fi

# Step 9: Verify deployment
echo "[9/9] Verifying deployment..."
echo ""
echo "--- Kubernetes Resources ---"
kubectl get pods -n production
echo ""
kubectl get services -n production
echo ""

echo "============================================="
echo "  Deployment Complete!"
echo "============================================="
echo ""
echo "Resources:"
echo "  Resource Group:  $RESOURCE_GROUP"
echo "  AKS Cluster:     $AKS_CLUSTER"
echo "  PostgreSQL:      $POSTGRES_FQDN"
echo "  Menu API:        https://$MENU_API_FQDN"
[ -n "${ORDER_API_IP:-}" ] && echo "  Order API:       http://$ORDER_API_IP"
[ -n "${PAYMENT_SERVICE_IP:-}" ] && echo "  Payment Service: http://$PAYMENT_SERVICE_IP"
[ -n "${WEBUI_FQDN:-}" ] && echo "  Web UI:          https://$WEBUI_FQDN"
[ -n "${JIRA_FQDN:-}" ] && echo "  Jira SM:         https://$JIRA_FQDN"
[ -n "${MCP_FQDN:-}" ] && echo "  MCP Atlassian:   https://$MCP_FQDN/mcp"
echo ""
echo "Endpoints saved to: ${ENV_FILE}"
echo ""
if [ -n "$SRE_MI_CLIENT_ID" ]; then
  echo "SRE Agent MCP Connector:"
  echo "  Identity:        id-contoso-meals-sre-agent"
  echo "  AZURE_CLIENT_ID: $SRE_MI_CLIENT_ID"
  echo ""
fi
if [ -n "$SRE_AGENT_PORTAL_URL" ]; then
  echo "SRE Agent (deployed via Bicep):"
  echo "  Portal URL:      $SRE_AGENT_PORTAL_URL"
  echo "  Access Level:    High (Reader + Contributor + Log Analytics Reader)"
  echo "  Mode:            Review"
  echo ""
fi
echo "Chaos Studio:"
echo "  Experiment:      exp-${PREFIX}-pod-kill"
echo "  Run from CLI:    az chaos experiment start --name exp-${PREFIX}-pod-kill --resource-group $RESOURCE_GROUP"
echo "  Run from portal: Azure Portal > Chaos Studio > Experiments > exp-${PREFIX}-pod-kill > Start"
echo ""
echo "Load Testing:"
echo "  Baseline test:   az load test-run create --load-test-resource $LOAD_TEST_RESOURCE --resource-group $RESOURCE_GROUP --test-id baseline --test-run-id baseline-\$(date +%Y%m%d-%H%M)"
echo "  Lunch rush test: az load test-run create --load-test-resource $LOAD_TEST_RESOURCE --resource-group $RESOURCE_GROUP --test-id lunch-rush --test-run-id lunch-rush-\$(date +%Y%m%d-%H%M)"
echo "  Local load gen:  ./scripts/generate-load.sh 30"
echo ""
echo "Next steps:"
echo "  1. Seed data:               ./scripts/seed-data.sh"
echo "  2. Run baseline load test:  ./scripts/generate-load.sh 30"
echo "  3. Set up Jira:             ./scripts/setup-jira.sh"
echo "  4. Open SRE Agent in portal and configure MCP, Teams, Knowledge Base"
echo "     (see demo-proposal.md Part 1)"
echo ""
