#!/bin/bash
set -euo pipefail

###############################################################################
# Contoso Meals - Post-Deploy Hook
# Runs after 'azd deploy' to:
#   1. Configure web-ui with AKS backend URLs
#   2. Generate .env file with all service endpoints
#   3. Configure Azure Load Testing tests with endpoint URLs
###############################################################################

echo ""
echo "============================================="
echo "  Post-Deploy: Configuring Services"
echo "============================================="
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_ROOT}/.env"

RESOURCE_GROUP=$(azd env get-value AZURE_RESOURCE_GROUP 2>/dev/null || azd env get-value resourceGroupName 2>/dev/null || echo "rg-contoso-meals")
AKS_CLUSTER_NAME=$(azd env get-value AZURE_AKS_CLUSTER_NAME 2>/dev/null || azd env get-value aksClusterName 2>/dev/null || echo "aks-contoso-meals")
LOAD_TEST_RESOURCE="lt-contoso-meals"

echo "Resource Group: $RESOURCE_GROUP"
echo "AKS Cluster:    $AKS_CLUSTER_NAME"
echo ""

# ─── Step 1: Ensure namespace exists & wait for LoadBalancer IPs ────
echo "[1/4] Waiting for AKS LoadBalancer external IPs..."
echo "  (Manifests are deployed by 'azd deploy' — no separate kubectl apply needed)"

# Get AKS credentials if not already configured
az aks get-credentials \
  --resource-group "$RESOURCE_GROUP" \
  --name "$AKS_CLUSTER_NAME" \
  --overwrite-existing --only-show-errors 2>/dev/null || true

# Ensure namespace exists (azd deploy should create it, but just in case)
kubectl apply -f "$PROJECT_ROOT/manifests/namespace.yaml" 2>/dev/null || true

echo "  Waiting for LoadBalancer external IPs..."

ORDER_API_IP=""
PAYMENT_SERVICE_IP=""

for i in $(seq 1 30); do
  ORDER_API_IP=$(kubectl get svc order-api -n production -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")
  PAYMENT_SERVICE_IP=$(kubectl get svc payment-service -n production -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")

  if [ -n "$ORDER_API_IP" ] && [ -n "$PAYMENT_SERVICE_IP" ]; then
    break
  fi
  echo "  Waiting for external IPs... (attempt $i/30)"
  sleep 10
done

echo "  Order API IP:       ${ORDER_API_IP:-not assigned}"
echo "  Payment Service IP: ${PAYMENT_SERVICE_IP:-not assigned}"
echo ""

# ─── Step 2: Update web-ui Container App with backend URLs ─────────
echo "[2/4] Updating web-ui Container App with backend API URLs..."

MENU_API_FQDN=$(az containerapp show \
  --name menu-api \
  --resource-group "$RESOURCE_GROUP" \
  --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")

ENV_VARS=""
[ -n "$MENU_API_FQDN" ] && ENV_VARS="MENU_API_URL=https://${MENU_API_FQDN}"
[ -n "$ORDER_API_IP" ] && ENV_VARS="$ENV_VARS ORDER_API_URL=http://${ORDER_API_IP}"
[ -n "$PAYMENT_SERVICE_IP" ] && ENV_VARS="$ENV_VARS PAYMENT_API_URL=http://${PAYMENT_SERVICE_IP}"

if [ -n "$ENV_VARS" ]; then
  az containerapp update \
    --name web-ui \
    --resource-group "$RESOURCE_GROUP" \
    --set-env-vars $ENV_VARS \
    --only-show-errors 2>/dev/null || echo "  WARNING: Failed to update web-ui env vars."
  echo "  web-ui backend URLs configured."
else
  echo "  WARNING: No backend URLs available. web-ui proxy may not work."
fi
echo ""

# ─── Step 3: Generate .env file ────────────────────────────────────
echo "[3/4] Generating .env file..."

WEBUI_FQDN=$(az containerapp show \
  --name web-ui \
  --resource-group "$RESOURCE_GROUP" \
  --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")

CONTAINER_APP_DOMAIN=$(az containerapp env show \
  --name "$(az containerapp show --name menu-api --resource-group "$RESOURCE_GROUP" --query "properties.managedEnvironmentId" -o tsv 2>/dev/null | xargs -I{} basename {})" \
  --resource-group "$RESOURCE_GROUP" \
  --query "properties.defaultDomain" -o tsv 2>/dev/null || echo "")

JIRA_FQDN=$(az containerapp show \
  --name jira-sm \
  --resource-group "$RESOURCE_GROUP" \
  --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")

MCP_FQDN=$(az containerapp show \
  --name mcp-atlassian \
  --resource-group "$RESOURCE_GROUP" \
  --query properties.configuration.ingress.fqdn -o tsv 2>/dev/null || echo "")

POSTGRES_FQDN=$(azd env get-value postgresServerFqdn 2>/dev/null || echo "")

SRE_AGENT_PORTAL_URL=$(azd env get-value sreAgentPortalUrl 2>/dev/null || echo "")
SRE_MI_CLIENT_ID=$(azd env get-value SRE_AGENT_MI_CLIENT_ID 2>/dev/null || \
  az identity show --name "id-contoso-meals-sre-agent" --resource-group "$RESOURCE_GROUP" --query clientId -o tsv 2>/dev/null || echo "")

{
  echo "# Contoso Meals - Service Endpoints"
  echo "# Auto-generated by post-deploy.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo ""
  echo "# Container App endpoints"
  echo "MENU_API_URL=https://${MENU_API_FQDN}"
  echo "WEB_UI_URL=https://${WEBUI_FQDN}"
  echo ""
  echo "# AKS LoadBalancer endpoints"
  echo "ORDER_API_URL=http://${ORDER_API_IP:-<pending>}"
  echo "PAYMENT_API_URL=http://${PAYMENT_SERVICE_IP:-<pending>}"
  echo ""
  echo "# Jira Service Management"
  echo "JIRA_URL=https://${JIRA_FQDN:-}"
  echo ""
  echo "# MCP Atlassian Server"
  echo "MCP_ATLASSIAN_URL=https://${MCP_FQDN:-}/mcp"
  echo ""
  echo "# Azure resource identifiers"
  echo "RESOURCE_GROUP=${RESOURCE_GROUP}"
  echo "AKS_CLUSTER=${AKS_CLUSTER_NAME}"
  echo "LOAD_TEST_RESOURCE=${LOAD_TEST_RESOURCE}"
  echo ""
  echo "# PostgreSQL"
  echo "POSTGRES_FQDN=${POSTGRES_FQDN}"
  echo ""
  echo "# SRE Agent"
  echo "SRE_AGENT_PORTAL_URL=${SRE_AGENT_PORTAL_URL:-}"
  echo "SRE_AGENT_IDENTITY_CLIENT_ID=${SRE_MI_CLIENT_ID:-}"
} > "$ENV_FILE"

echo "  .env file written to ${ENV_FILE}"
echo ""

# ─── Step 4: Configure Azure Load Testing ──────────────────────────
echo "[4/4] Configuring Azure Load Testing tests..."

MENU_API_HOST="${MENU_API_FQDN}"
ORDER_API_HOST="${ORDER_API_IP:-}"
PAYMENT_HOST="${PAYMENT_SERVICE_IP:-}"

if [ -n "$ORDER_API_HOST" ] && [ -n "$PAYMENT_HOST" ]; then
  LOAD_TEST_ENV="MENU_API_HOST=${MENU_API_HOST} ORDER_API_HOST=${ORDER_API_HOST} PAYMENT_HOST=${PAYMENT_HOST}"

  # Create or update baseline test
  if az load test show --load-test-resource "$LOAD_TEST_RESOURCE" --resource-group "$RESOURCE_GROUP" --test-id "baseline" -o none 2>/dev/null; then
    echo "  Updating existing baseline test..."
    az load test update \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "baseline" \
      --test-plan "$PROJECT_ROOT/load-tests/baseline.jmx" \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  else
    echo "  Creating baseline test..."
    az load test create \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "baseline" \
      --display-name "Contoso Meals - Baseline Traffic" \
      --test-plan "$PROJECT_ROOT/load-tests/baseline.jmx" \
      --engine-instances 1 \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  fi
  echo "  Baseline load test configured."

  # Create or update lunch-rush test
  if az load test show --load-test-resource "$LOAD_TEST_RESOURCE" --resource-group "$RESOURCE_GROUP" --test-id "lunch-rush" -o none 2>/dev/null; then
    echo "  Updating existing lunch-rush test..."
    az load test update \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "lunch-rush" \
      --test-plan "$PROJECT_ROOT/load-tests/lunch-rush.jmx" \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  else
    echo "  Creating lunch-rush test..."
    az load test create \
      --load-test-resource "$LOAD_TEST_RESOURCE" \
      --resource-group "$RESOURCE_GROUP" \
      --test-id "lunch-rush" \
      --display-name "Contoso Meals - Lunch Rush" \
      --test-plan "$PROJECT_ROOT/load-tests/lunch-rush.jmx" \
      --engine-instances 1 \
      --env $LOAD_TEST_ENV \
      --only-show-errors -o none
  fi
  echo "  Lunch rush load test configured."
else
  echo "  WARNING: AKS IPs not available. Skipping load test configuration."
  echo "  Run manually: az load test create --load-test-resource $LOAD_TEST_RESOURCE ..."
fi

echo ""
echo "============================================="
echo "  Post-Deploy Complete"
echo "============================================="
echo ""
echo "  .env:           ${ENV_FILE}"
echo "  Menu API:       https://${MENU_API_FQDN}"
[ -n "${ORDER_API_IP:-}" ] && echo "  Order API:      http://${ORDER_API_IP}"
[ -n "${PAYMENT_SERVICE_IP:-}" ] && echo "  Payment Service: http://${PAYMENT_SERVICE_IP}"
echo ""
echo "  Next: seed data with ./scripts/seed-data.sh"
echo ""
